/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 * Regenerated: 2026-05-21T23:34:18.559Z
 */

declare module '@bemedev/app' {
  interface Register {
    actions: {
      paths: {
        map: {
          targets: '/idle'[];
          initial?: 'idle';
          states?: {
            idle: { targets: '/'[] };
          };
        };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: never;
        delays: never;
        guards: never;
      };
      pContext?: unknown;
      tags?: never;
    };
  }
}

export {};
