/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 * Regenerated: 2026-04-24T15:26:49.467Z
 */

declare module "@bemedev/app" {
  interface Register {
    actions: {
      paths: {
        map: {
          targets: "/idle"[];
          initial?: "idle";
          states?: {
            idle: { targets: "/"[] };
          };
        };
        all: "/" | "/idle";
      };
      events: "OINC";
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: "tito";
        delays: never;
        guards: never;
      };
      pContext?: unknown;
      tags?: never;
    };
  }
}

export {};
